#!/bin/bash /bin/bunny
source config.sh
TARGET windows
ATTACKMODE HID VID 03EB PID 2401
QUACK GUI r
QUACK DELAY 100
QUACK STRING $program
QUACK ENTER
QUACK DELAY 1000
QUACK STRING $text
LED R B BLINK 250